- hosts: localhost
  tasks:
  - name: Create temp directory for artifacts
    tempfile:
      state: directory
      suffix: packages
    register: temp_packages

  - name: Calculate Settings
    set_fact:
      download_url: "https://github.com/Inok/ansible-awx-demo/archive/master.zip"
      artifact_archive_path: "{{ temp_packages.path }}/package.zip"
      artifact_data_path: "{{ temp_packages.path }}/package_data"

  - name: Download the Artifact
    get_url:
      url: "{{ download_url }}"
      dest: "{{ artifact_archive_path }}"

  - name: Create a directory if it does not exist
    file:
      path: "{{ artifact_data_path }}"
      state: directory
      mode: '0755'

  - name: Unarchive the Artifact
    unarchive:
      src: "{{ artifact_archive_path }}"
      dest: "{{ artifact_data_path }}"
      remote_src: yes

- hosts: web
  tasks:
  - name: Include web tasks from artifact
    include_tasks: "{{ hostvars['localhost']['artifact_data_path'] }}/ansible-awx-demo-master/artifact/deploy-web.yml"