- hosts: web
  tasks:
    - name: Install .NET Framework 4.6.2
      win_chocolatey:
        name: dotnet4.6.2
        state: present

    - name: Install IIS Web-Server with sub features and management tools
      win_feature:
        name: Web-Server,Web-Common-Http,Web-Static-Content,Web-Health,Web-Performance,Web-Security,Web-App-Dev,Web-Asp$        state: present
      register: win_feature

    - name: Reboot if installing Web-Server feature requires it
      win_reboot:
      when: win_feature.reboot_required

    - name: Remove Default Web Site
      win_iis_website:
        name: "Default Web Site"
        state: absent